# Generated by Django 5.0.6 on 2024-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0007_pdffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='pdf',
            new_name='pdf_file',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='title',
            field=models.CharField(default='default title', max_length=100),
        ),
    ]
